apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: openfaas-fn
type: Opaque
data:
  # Encode en base64 ! Par exemple 'faasuser' => 'ZmFhc3VzZXI='
  POSTGRES_USER: ZmFhc3VzZXI=
  POSTGRES_PASSWORD: ZmFhcXNwYXNz
  POSTGRES_DB: dXNlcnNkYg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: openfaas-fn
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
